#!/bin/bash

docker build \
  --no-cache \
  -t dm-count-report-generation-service:experimental \
  .

docker run \
  --volume /Users/dv/Documents/abb/dm-count-report-generation-service:/app/ \
  --volume /Users/dv/Documents/abb/dm-count-report-generation-service/test-config:/config/ \
  --env NODE_ENV="development" \
  --env DISABLE_DEBUG_ENDPOINT="false" \
  --env ADMIN_UNIT_ENDPOINT="http://localhost:8890/sparql" \
  --env REPORT_ENDPOINT="http://localhost:8890/sparql" \
  --env SHOW_SPARQL_QUERIES="true" \
  --env LIMIT_NUMBER_ADMIN_UNITS=5 \
  --env SERVER_PORT=4199 \
  --hostname "dm-count-report-generation-service" \
  --network="host" \
  -it \
  dm-count-report-generation-service:experimental \

echo "Run script stopped"
