steps:
  install:
    image: woodpeckerci/plugin-node-pm
    commands:
      - npm ci
  release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
      access: public
      tag: beta
when:
  event: push
  branch: feature/*