steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64,linux/arm64
      repo: ${CI_REPO%%-service}
      tags: '${CI_COMMIT_TAG##v}'
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  - event: tag
    ref: refs/tags/v*